CREATE DATABASE IF NOT EXISTS tongquangdat2410900022_exam
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE tongquangdat2410900022_exam;

CREATE TABLE IF NOT EXISTS TqdEmployee (
    Id INT NOT NULL AUTO_INCREMENT,
    TqdName VARCHAR(100) NOT NULL,
    TqdGender VARCHAR(10) NOT NULL,
    TqdBirthDay DATE NOT NULL,
    TqdEmail VARCHAR(254) NULL,
    TqdPhone VARCHAR(20) NULL,
    TqdActive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TqdStudent (
    Id INT NOT NULL AUTO_INCREMENT,
    TqdName VARCHAR(100) NOT NULL,
    TqdGender VARCHAR(10) NOT NULL,
    TqdBirthDay DATE NOT NULL,
    TqdEmail VARCHAR(254) NULL,
    TqdPhone VARCHAR(20) NULL,
    TqdActive BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;